# ================================
# Production Profile
# ================================
spring:
  datasource:
    url: jdbc:postgresql://shuttle.proxy.rlwy.net:44842/railway
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:WLgLriNFvnerPPYxHdwmELXQbuscYmov}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

# Logging - minimal for production
logging:
  level:
    com.pickleball: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
